### PR TITLE
Don't explode if child process is already dead

### LINKED ISSUE #5: Prevent kill errors
When pressing ^C, `Process.kill` sometimes happens with the process already exited (maybe cleanly) before it's able to kill it. It's a harmless error, but it can be suppressed to make things less confusing.

```
[npm-pipeline-rails] Terminating 'npm run start' [78253]
/.../gems/npm-pipeline-rails-1.1.3/lib/npm-pipeline-rails/railtie.rb:28:in `kill': No such process (Errno::ESRCH)
        from /.../gems/npm-pipeline-rails-1.1.3/lib/npm-pipeline-rails/railtie.rb:28:in `block in background'
```

### PR DESCRIPTION
**Pull request by mikker**
My brunch watcher is always, always already dead at this point (why? Will we ever know?)

Fixes #5 

Thanks!

### CODE REVIEW

**Comment by rstacruz** [comment]
Thanks for this! Would love to know what you think of npm-pipeline-rails and how you're using it.

**Comment by rstacruz** [comment]
1.6.1 is out with this fix, thanks!

**Comment by mikker** [comment]
Great! Glad to help. I'm using it with as many Rails projects as I can. Usually with brunch but I could definitely imagine doing it with Webpack too.

As you write it yourself, the asset pipeline is too old and cumbersome and the web has come far since it was made. Doing even the smallest amount of front-end – javascript OR css – without access to `npm` and `node_modules` gets tedious fast.

I think your lib here does the minimally required setting up to allow maximum customisability. Just as I'd want it to.

**Comment by mikker** [comment]
I sometimes did this along with a Webpack dev server script:

In the bottom of development.rb:

```ruby
if defined?(Rails::Server)
  class WebpackDevServer
    def self.run!
      return @pid if @pid

      @pid = Process.spawn("./webpack.server.js")
      Signal.trap("EXIT") { Process.kill(9, pid) }

      @pid
    end
  end

  WebpackDevServer.run!
end
```

Which I suppose is a somewhat brutal way of doing what this gem is doing 😄

**Pull request merged**
