### PR TITLE
Add option to toggle npm install on rails server

### PR DESCRIPTION
**Pull request by mikker**
Not sure about the name but I wanted this.
If you like the idea I can add it to the readme as well?

### CODE REVIEW

**Comment by mikker** [comment]
Booting Rails takes lang enough by itself 😁

**Comment by rstacruz** [comment]
Yes this makes sense. Sorry for taking so long!

**Comment by mikker** [comment]
No worries! 🎉

**Comment by mikker** [comment]
So... merge? 😄

**Comment by rstacruz** [comment]
1.7.0 is out today!

Btw, I'm implementing Webpack "support" at #18, I see you've been using npm-pipeline-rails so feel free to drop by and chime in with your feedback. :)

**Pull request merged**
